spring.application.name=mobileBE

server.port=${SVPORT}

spring.profiles.active=dev

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

app.redis.enabled=${USE_REDIS:true}
spring.data.redis.host=localhost
spring.data.redis.port=6379
# ??m b?o Hibernate dùng ?úng múi gi? khi ??c/ghi vào DB
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Ho_Chi_Minh

# C?u hình Jackson tr? v? ?úng múi gi? Vi?t Nam khi format JSON
spring.jackson.time-zone=Asia/Ho_Chi_Minh
# T?t ch? ?? ghi ngày tháng d??i d?ng timestamp s?
spring.jackson.serialization.objectMapper.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);

app.jwt.secretKey=${SECRETKEY}