spring.application.name=dev

SVPORT=8080

DB_URL=jdbc:mysql://localhost:3307/mobilequanlythuvien?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
DB_USER= quanlythuvien
DB_PASS=123456

SECRETKEY=KJt6yaCV+FS418hO5vHFbb4kC04pW5OPgZMM1p36NukFEje2dEO02/LEygYlXaPhs7Qqnm4L25F38uMRndxrdA==

USE_REDIS=false